export const FACTORES_RIESGO_OPTIONS = [
  "Crisis no normativas",
  "Cesantía jefe de hogar o sostenedor",
  "VIF",
  "Embarazo de riesgo",
  "Consumo OH - Drogas",
  "Conductas delictuales",
  "Deficiencia vivienda y/o hacinamiento",
  "Patología o Trastorno psiquiatrico",
  "Mal nutrición",
  "Discapacidad - dependencia (desmovilizado)",
  "Enfermedad crónica descompensada",
  "Hospitalizaciones frecuentes",
  "Disfunción familiar",
  "Familia monoparental",
  "Abandono, aislamiento o situación de calle",
  "Bajo nivel socio cultural",
  "Abuso sexual y/o violación",
  "Deficiencia red de apoyo comunitario",
  "Entorno social de riesgo",
  "Deficiencias saneamiento básico",
  "Deficiencia equipamiento urbano y comunitario",
  "Sobreendeudamiento",
  "Estrés laboral",
  "Disfunción laboral",
  "Sedentarismo",
  "Tabaquismo"
];
